name: "Bug Report"
description: "File a bug report to help us improve"
labels: [need/triage, kind/bug]

- type: textarea
  id: version
  attributes:
    label: DataSwap Version
    render: text
    description: 
    placeholder: 
  validations:
    required: false

- type: textarea
  id: ReproSteps
  attributes:
    label: Repro Steps
    description: "Steps to reproduce the behavior"
    value: |
      1. Run '...'
      2. Do '...'
      3. See error '...'
      ...
  validations:
    required: false

- type: textarea
  id: Description
  attributes:
    label: Describe the Bug
    description: |
      This is where you get to tell us what went wrong, when doing so, please try to provide a clear and concise description of the bug with all related information:
      * What you were doing when you experienced the bug?
      * Any *error* messages you saw, *where* you saw them, and what you believe may have caused them (if you have any ideas).
      * What is the expected behaviour?
  validations:
    required: true

- type: textarea
  id: extraInfo
  attributes:
    label: Logging Information
    render: text
    description: |
      Please provide debug logs of the problem, remember you can get set log level control for:
  validations:
    required: false

- type: file
  id: screenshot
  attributes:
    label: Upload Screenshot
    description: "You can upload a screenshot to help illustrate the issue."
  validations:
    required: false