name: DockerHub Image Run

on: workflow_dispatch

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Docker container
      run: |
        docker run -d -p 1234:1234 --name localnetwork siriusyim/lotus-devnet:0.1.0
        sleep 60
    - name: lotus wallet list
      run: |
        docker ps -a
        docker ps
        docker image ls
        docker exec -it localnetwork ls -la /var/tmp/filecoin-proof-parameters/*
        docker exec -it localnetwork journalctl -u lotus-miner.service -f
        docker exec -it localnetwork /usr/local/bin/lotus wallet list
