name: DockerHub Image Run

on: workflow_dispatch

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: install tmux
      run: |
        sudo cat /etc/issue
        sudo apt update
        sudo apt install -y tmux
        sudo tmux version

    - name: Run Docker container
      run: |
        docker run -d -p 1234:1234 --name localnetwork siriusyim/lotus-devnet:0.2.0
        docker ps -a
        
    - name: lotus wallet list
      run: |
        docker ps -a
        docker image ls
        docker logs localnetwork
        docker exec -it localnetwork ls -la /var/tmp/filecoin-proof-parameters/*
        docker exec -it localnetwork journalctl -u lotus-miner.service -f
        docker exec -it localnetwork /usr/local/bin/lotus wallet list
