name: DockerHub Image Run

on: workflow_dispatch

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Docker container
      run: |
        docker run -d -p 8080:8080 mysql:5.7
        docker ps
        docker exec -it some-mysql mysql --version
