name: DockerHub Image Run

on: workflow_dispatch

jobs:
  run-container:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: install tmux
      run: |
        sudo cat /etc/issue
        sudo apt update
        sudo apt list --upgradable
        sudo apt-get install -y ca-certificates build-essential clang ocl-icd-opencl-dev ocl-icd-libopencl1 jq libhwloc-dev tmux

    - name: Run Docker container
      run: |
        docker run -d -p 1234:1234 -v /opt/:/root/ --name localnetwork siriusyim/lotus-devnet:0.2.0
        docker logs localnetwork
        sleep 60
        docker ps -a
        
    - name: lotus wallet list
      run: |
        docker ps -a
        docker image ls
        docker logs localnetwork
        docker exec -i localnetwork /usr/local/bin/lotus wallet list
