name: DockerHub Image Run

on: workflow_dispatch

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Docker container
      run: |
        docker run -d --name my-mysql -e MYSQL_ROOT_PASSWORD=test@123 mysql:5.7
        docker ps
        docker image ls
        docker exec -it my-mysql ls
