name: DockerHub Image Run

on: workflow_dispatch

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Docker container
      run: |
        docker run -d -p 61234:1234 glif/lotus:v1.25.0-gw-estimategas-calibnet-arm64
        docker ps
