name: DockerHub Image Run

on: workflow_dispatch

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Docker container
      run: |
        docker run -d --name localnetwork siriusyim/lotus-devnet:0.1.0
    - name: Run Docker container
      run: |
        docker ps
        docker image ls
        docker exec -it localnetwork /usr/local/bin/lotus wallet list
