name: DockerHub Image Run

on: workflow_dispatch

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Docker container
      run: |
        docker run -d -p 8080:8080 mysql:latest
        docker run -it --rm mysql:latest --verbose --help
        docker exec -it mysql:latest bash
