name: Solhint Analysis

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  solhint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Solhint
        run: npm install -g solhint

      - name: Run Solhint Analysis
        run: solhint

