name: Solhint Analysis

on:
  pull_request:
    paths:
      - '**/*.sol'
    branches:
      - main

jobs:
  solhint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Solhint
        run: |
          npm install -g solhint
          solhint -V

      - name: Get changed files
        id: files
        run: |
          echo "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.sol$')" > changed_files.txt

      - name: Run Solhint Analysis
        run: |
          echo "Running Solhint analysis..."
          cat changed_files.txt | xargs solhint

      - name: Display Completed Message
        run: echo "Solhint analysis completed."
