name: Solhint Analysis

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  solhint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        solidity-version: [0.8.21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Solhint And Prettier
        run: |
          npm uninstall -g solhint solhint-plugin-prettier prettier-plugin-solidity
          npm install -g solhint solhint-plugin-prettier prettier-plugin-solidity

      - name: Run Solhint Analysis
        run: |
          echo "Running Solhint analysis..."
          solhint "**/*.sol"

      - name: Display Completed Message
        run: echo "Solhint analysis completed."