name: Solhint Analysis

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  solhint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Solhint
        run: |
          npm install -g solhint solhint-plugin-prettier
          solhint -V

      - name: Run Solhint Analysis
        run: |
          solhint **/*.sol
          shell: bash

      - name: Display Completed Message
        run: echo "Solhint analysis completed."
