name: Solhint Analysis

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  solhint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        solidity-version: [0.8.21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Solhint
        run: |
          npm install -g solhint
          solhint -V

      - name: Run Solhint Analysis
        run: |
          solhint **/*.sol
          shell: bash

      - name: Display Completed Message
        run: echo "Solhint analysis completed."